# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '我的小咖秀' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'pop'
end

